kind = "mobile"
previewPath = "/mobile/"
title = "Quindici Mobile"
version = "1.0.0"
id = "artifacts/quindici-mobile"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/mobile/" ]
localPort = 25614

[services.development]
run = "pnpm --filter @workspace/quindici-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/quindici-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/quindici-mobile", "run", "serve" ]

[services.env]
PORT = "25614"
BASE_PATH = "/mobile/"
